import CreditInfo from "./CreditInfo";

export const mockData: CreditInfo[] = [
    {
        companyName: "Exa Company",
        address: "123  Street",
        registrationDate: "2023-01-01",
        numberOfEmployees: 650,
        raisedCapital: 10000,
        turnover: 50000,
        netProfit: 2000,
        contactNumber: "123-456-7890",
        contactEmail: "info@example.com",
        companyWebsite: "https://www.example.com",
        loanAmount: 50000,
        loanInterest: 5,
        accountStatus: 'active'
    },
    {
        companyName: "Example Company 2",
        address: "123 Eple Street",
        registrationDate: "2023-06-01",
        numberOfEmployees: 500,
        raisedCapital: 1300030,
        turnover: 504400,
        netProfit: 300000,
        contactNumber: "123-456-7890",
        contactEmail: "info@example.com",
        companyWebsite: "https://www.example.com",
        loanAmount: 50000,
        loanInterest: 5,
        accountStatus: 'closed'
    },
    {
        companyName: "Example Company 3",
        address: "1Example Street",
        registrationDate: "2018-01-01",
        numberOfEmployees: 50,
        raisedCapital: 133000,
        turnover: 599900,
        netProfit: 200000,
        contactNumber: "123-456-7890",
        contactEmail: "info@example.com",
        companyWebsite: "https://www.example.com",
        loanAmount: 50000,
        loanInterest: 5,
        accountStatus: 'active'
    },
    {
        companyName: "Example Company 4",
        address: "1Example Street 4",
        registrationDate: "2023-04-01",
        numberOfEmployees: 750,
        raisedCapital: 137540,
        turnover: 558800,
        netProfit: 23900,
        contactNumber: "123-456-7890",
        contactEmail: "info@example.com",
        companyWebsite: "https://www.example.com",
        loanAmount: 50000,
        loanInterest: 5,
        accountStatus: 'active'
    },
    {
        companyName: "Example Company 5",
        address: "1Example Street 5",
        registrationDate: "2021-04-06",
        numberOfEmployees: 430,
        raisedCapital: 137430,
        turnover: 54300,
        netProfit: 23410,
        contactNumber: "123-456-7890",
        contactEmail: "info@example.com",
        companyWebsite: "https://www.example.com",
        loanAmount: 50000,
        loanInterest: 5,
        accountStatus: 'closed'
    },
    {
        companyName: "Bright Future LLC",
        address: "123 Sunshine Blvd, Sunnyvale",
        registrationDate: "2020-02-15",
        numberOfEmployees: 120,
        raisedCapital: 2000000,
        turnover: 500000,
        netProfit: 150000,
        contactNumber: "555-0102",
        contactEmail: "info@brightfuture.com",
        companyWebsite: "https://www.brightfuture.com",
        loanAmount: 300000,
        loanInterest: 4.5,
        accountStatus: 'active'
      },
      {
        companyName: "Tech Innovate Inc.",
        address: "456 Tech Park Ave, Silicon Valley",
        registrationDate: "2019-08-20",
        numberOfEmployees: 200,
        raisedCapital: 5000000,
        turnover: 1200000,
        netProfit: 300000,
        contactNumber: "555-0203",
        contactEmail: "contact@techinnovate.com",
        companyWebsite: "https://www.techinnovate.com",
        loanAmount: 500000,
        loanInterest: 5,
        accountStatus: 'closed'
      },
      {
        companyName: "Quantum Solutions",
        address: "88 Innovation Drive, Techville",
        registrationDate: "2021-04-10",
        numberOfEmployees: 150,
        raisedCapital: 3000000,
        turnover: 750000,
        netProfit: 200000,
        contactNumber: "123-456-7890",
        contactEmail: "contact@quantumsol.com",
        companyWebsite: "https://www.quantumsol.com",
        loanAmount: 500000,
        loanInterest: 5.5,
        accountStatus: 'active'
      },
      {
        companyName: "Green Energy Inc.",
        address: "22 Eco Lane, Greenfield",
        registrationDate: "2019-07-15",
        numberOfEmployees: 80,
        raisedCapital: 1200000,
        turnover: 500000,
        netProfit: 120000,
        contactNumber: "123-456-7888",
        contactEmail: "info@greenenergy.com",
        companyWebsite: "https://www.greenenergy.com",
        loanAmount: 250000,
        loanInterest: 4,
        accountStatus: 'active'
      },
      {
        companyName: "NextGen Innovators",
        address: "101 Future Road, Silicon Valley",
        registrationDate: "2020-01-20",
        numberOfEmployees: 200,
        raisedCapital: 4000000,
        turnover: 1500000,
        netProfit: 500000,
        contactNumber: "123-456-7777",
        contactEmail: "hello@nextgeninnov.com",
        companyWebsite: "https://www.nextgeninnov.com",
        loanAmount: 600000,
        loanInterest: 6,
        accountStatus: 'closed'
      },
];